import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Harriet Oteng',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='border-2 border-black h-[4rem]'>
          Nav
        </header>
        <main className='min-h-[calc(100vh-7rem)] border-2 border-blue-500'>{children}</main>
        <footer className='h-[3rem] border-2 border-red-500'>by HOteng</footer>
      </body>
    </html>
  )
}
